<?php
// $Id: custom_breadcrumbs.module,v 1.6.2.4 2008/09/22 02:25:43 eaton Exp $

/**
 * Implementation of hook_menu().
 */
function custom_breadcrumbs_menu() {
  $items = array();

  $items['admin/build/custom_breadcrumbs'] = array(
    'title' => 'Custom breadcrumbs',
    'description' => 'Add custom breadcrumb trails for content types.',
    'page callback' => 'custom_breadcrumbs_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer custom breadcrumbs'),
    'file' => 'custom_breadcrumbs.admin.inc',
  );

  $items['admin/build/custom_breadcrumbs/add'] = array(
    'title' => 'Add custom breadcrumb',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_breadcrumbs_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer custom breadcrumbs'),
    'file' => 'custom_breadcrumbs.admin.inc',
  );

  $items['admin/build/custom_breadcrumbs/edit'] = array(
    'title' => 'Edit custom breadcrumb',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_breadcrumbs_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer custom breadcrumbs'),
    'file' => 'custom_breadcrumbs.admin.inc',
  );

  return $items;
}

function custom_breadcrumbs_perm() {
  return array('administer custom breadcrumbs', 'use php in custom breadcrumbs');
}

function custom_breadcrumbs_nodeapi($node, $op, $teaser, $page) {
  if ($op == 'alter' && !$teaser && $page) {
    if ($breadcrumb = _custom_breadcrumbs_load_for_type($node)) {
      $titles = preg_split("/[\n]+/", $breadcrumb->titles);
      $paths = preg_split("/[\n]+/", $breadcrumb->paths);

      $titles = module_exists('token') ? token_replace($titles, 'node', $node) : $titles;
      $paths = module_exists('token') ? token_replace($paths, 'node', $node) : $paths;

      $trail = array(l(t('Home'), '<front>'));
      $location = array();
      for ($i = 0; $i < count($titles); $i++) {
        // Skip empty titles
        if ($title = trim($titles[$i])) {
          // Output plaintext instead of a link if there is a title without a path.
          $path = trim($paths[$i]);
          if (strlen($path) > 0 && $path != '<none>') {
            $trail[] = l($title, trim($paths[$i]));
            $location[$i] = menu_get_item(drupal_get_normal_path($paths[$i]));          }
          else {
            $trail[] = check_plain($title);
          }
        }
      }
      drupal_set_breadcrumb($trail);
      if ($breadcrumb->set_active_menu) {
        $location[] = menu_get_item();
        menu_set_active_trail($location);
      }
    }
  }

}

function _custom_breadcrumbs_load_breadcrumb($bid) {
  $sql = 'SELECT * FROM {custom_breadcrumb} WHERE bid = %d';
  $result = db_query($sql, $bid);
  $breadcrumb = db_fetch_object($result);
  return $breadcrumb;
}

function _custom_breadcrumbs_load_for_type($node) {
  $sql = "SELECT * FROM {custom_breadcrumb} WHERE node_type = '%s'";
  $result = db_query($sql, $node->type);
  while ($breadcrumb = db_fetch_object($result)) {
    if (!empty($breadcrumb->visibility_php)) {
      // Use PHP code to check the visibility.
      ob_start();
      $result = eval(trim($breadcrumb->visibility_php));
      ob_end_clean();
      if ($result == TRUE) {
        return $breadcrumb;
      }
    }
    else {
      return $breadcrumb;
    }
  }
}

function _custom_breadcrumbs_load_all_breadcrumbs($refresh = FALSE) {
  static $breadcrumbs;
  if ($refresh || !isset($breadcrumbs)) {
    $sql = 'SELECT * FROM {custom_breadcrumb}';
    $result = db_query($sql);

    $breadcrumbs = array();
    while ($breadcrumb = db_fetch_object($result)) {
      $breadcrumbs[] = $breadcrumb;
    }
  }
  return $breadcrumbs;
}

function custom_breadcrumbs_save_breadcrumb($breadcrumb = NULL) {
  if (is_array($breadcrumb->paths)) {
    $breadcrumb->paths = implode("\n", $breadcrumb->paths);
  }
  if (is_array($breadcrumb->titles)) {
    $breadcrumb->titles = implode("\n", $breadcrumb->titles);
  }

  if (isset($breadcrumb->bid)) {
    drupal_write_record('custom_breadcrumb', $breadcrumb, 'bid');
  }
  else {
    drupal_write_record('custom_breadcrumb', $breadcrumb);
  }
}

function _custom_breadcrumbs_delete_breadcrumb($bid) {
  $sql = 'DELETE FROM {custom_breadcrumb} WHERE bid = %d';
  db_query($sql, $bid);
}
